### ISSUE TITLE
Unminified version of vimeo-timing-object-demo?

### ISSUE THREAD

**Issue by MattTheRed** [salmoro/vimeo-timing-object-demo#1]
I saw that you have an implementation of the `TimingObject` spec using Firebase as a backend and was wondering if you could share the unminified code to your repo? Impressive demo!

**Comment by salmoro** [comment]
@MattTheRed here's the link to that implementation:

https://github.com/salmoro/abstract-timing-provider/blob/master/lib/datasources/firebase-datasource.ts

It's a pretty simple implementation but assuming the clients' clocks are trusted to be accurate then this works just fine.
